apiVersion: v1
kind: ConfigMap
Metadata:
  name: {{ include "minecraft-bedrock.name" . }}-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

data:
{{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}