apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "minecraft-bedrock.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "minecraft-bedrock.name" . }}
    helm.sh/chart: {{ include "minecraft-bedrock.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minecraft-bedrock.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "minecraft-bedrock.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          ports:
            - name: bedrock
              containerPort: 19132
              hostPort: 19132
              protocol: UDP
          resources:
{{ toYaml .Values.resources | indent 11 }}
          env:
          - name: BEDROCK_DOWNLOAD_ZIP
            value: {{ .Values.minecraftServer.bedrockDownloadUrl | quote }}
          volumeMounts:
          - name: datadir
            mountPath: /home/bedrock/bedrock_server/
          - name: config-volume
            mountPath: /home/bedrock/bedrock_server/ops.json
            subPath: ops.json
          - name: config-volume
            mountPath: /home/bedrock/bedrock_server/server.properties
            subPath: server.properties
          - name: config-volume
            mountPath: /home/bedrock/bedrock_server/whitelist.properties
            subPath: whitelist.properties
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "minecraft-bedrock.name" . }}-config
        - name: datadir
        {{- if .Values.persistence.dataDir.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "minecraft-bedrock.name" . }}-datadir
        {{- else }}
          emptyDir: {}
        {{- end }}